[package]
name = "elven_canopy_gdext"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
elven_canopy_sim = { path = "../elven_canopy_sim" }
godot = { version = "0.4.5", features = ["api-4-5"] }
serde_json = "1"
